<?php $critical = count(array_filter($data['rows'], static function ($row) { return $row['quantidade'] < $row['quantidade_minima']; })); ?>
<div class="section-heading"><div><p class="eyebrow">PEÇAS DISPONÍVEIS</p><h2>Saldo e reposição</h2></div><span class="badge <?= $critical ? 'badge-alert' : '' ?>"><?= $critical ?> abaixo do mínimo</span></div>
<?php if (!$data['rows']): ?><p class="empty-state">Cadastre uma peça para começar a controlar o estoque.</p><a class="button" href="index.php?opcao=produto">Cadastrar peça</a><?php else: ?>
<div class="table-wrap" tabindex="0" role="region" aria-label="Saldo do estoque"><table><thead><tr><th scope="col">Peça / SKU</th><th scope="col">Quantidade atual</th><th scope="col">Mínimo</th><th scope="col">Situação</th></tr></thead><tbody>
<?php foreach ($data['rows'] as $row): $low = $row['quantidade'] < $row['quantidade_minima']; ?><tr class="<?= $low ? 'stock-low' : '' ?>"><td><strong><?= h($row['nome']) ?></strong><small><?= h($row['sku']) ?></small></td><td class="numeric"><?= h($row['quantidade']) ?></td><td><?= h($row['quantidade_minima']) ?></td><td><span class="badge <?= $low ? 'badge-alert' : '' ?>"><?= $low ? 'Reposição necessária' : 'Saldo adequado' ?></span></td></tr><?php endforeach; ?>
</tbody></table></div>
<div class="section-heading divided"><h2>Registrar movimentação</h2></div>
<form method="post" action="index.php?opcao=estoque" class="form-grid">
    <?php csrf_input(); ?><input type="hidden" name="acao" value="movimentar">
    <div class="field"><label for="produto_id">Peça</label><select id="produto_id" name="produto_id" required data-stock-select><option value="">Selecione uma peça</option><?php foreach ($data['rows'] as $row): ?><option value="<?= h($row['id']) ?>" data-minimo="<?= h($row['quantidade_minima']) ?>" <?= raw($_POST, 'produto_id') === (string) $row['id'] ? 'selected' : '' ?>><?= h($row['nome']) ?> — saldo <?= h($row['quantidade']) ?></option><?php endforeach; ?></select></div>
    <div class="field"><label for="tipo">Tipo de movimentação</label><select id="tipo" name="tipo" required><option value="entrada">Entrada / Reposição</option><option value="saida" <?= raw($_POST, 'tipo') === 'saida' ? 'selected' : '' ?>>Saída / Perda / Uso interno</option></select></div>
    <div class="field"><label for="quantidade">Quantidade movimentada</label><input id="quantidade" name="quantidade" type="number" min="1" max="1000000" step="1" required value="<?= h(raw($_POST, 'quantidade')) ?>"></div>
    <div class="field"><label for="quantidade_minima">Estoque mínimo após movimentação</label><input id="quantidade_minima" name="quantidade_minima" type="number" min="0" max="1000000" step="1" required value="<?= h(raw($_POST, 'quantidade_minima') !== '' ? raw($_POST, 'quantidade_minima') : '5') ?>"></div>
    <div class="field full"><label for="motivo">Motivo</label><input id="motivo" name="motivo" maxlength="200" placeholder="Ex.: Reposição do fornecedor ou peça danificada" required value="<?= h(raw($_POST, 'motivo')) ?>"></div>
    <div class="form-actions"><button type="submit">Registrar movimentação</button><span class="help">Vendas já baixam o estoque automaticamente.</span></div>
</form>
<?php endif; ?>
<div class="section-heading divided"><h2>Últimas 50 movimentações</h2></div>
<?php if (!$data['movements']): ?><p class="empty-state">Nenhuma movimentação registrada.</p><?php else: ?><div class="table-wrap" tabindex="0" role="region" aria-label="Histórico de estoque"><table><thead><tr><th scope="col">Data</th><th scope="col">Peça</th><th scope="col">Tipo</th><th scope="col">Quantidade</th><th scope="col">Motivo</th></tr></thead><tbody><?php foreach ($data['movements'] as $row): ?><tr><td><?= h(date('d/m/Y H:i', strtotime($row['criado_em']))) ?></td><td><?= h($row['nome']) ?></td><td><?= h($row['tipo']) ?></td><td><?= h($row['quantidade']) ?></td><td><?= h($row['motivo']) ?><?= $row['venda_id'] ? ' · Venda #' . h($row['venda_id']) : '' ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
