<?php $form = $error && raw($_POST, 'acao') === 'salvar' ? $_POST : $data['edit']; ?>
<div class="section-heading"><div><p class="eyebrow">CATÁLOGO DE PEÇAS</p><h2><?= raw($form, 'id') ? 'Editar peça' : 'Nova peça para moto' ?></h2></div><span class="badge"><?= count($data['rows']) ?> produtos</span></div>
<form method="post" action="index.php?opcao=produto" class="form-grid">
    <?php csrf_input(); ?><input type="hidden" name="acao" value="salvar"><input type="hidden" name="id" value="<?= h(raw($form, 'id')) ?>">
    <div class="field"><label for="sku">Código da peça (SKU)</label><input id="sku" name="sku" maxlength="40" placeholder="Ex.: FREIO-001" required value="<?= h(raw($form, 'sku')) ?>"></div>
    <div class="field"><label for="nome">Nome da peça</label><input id="nome" name="nome" maxlength="120" placeholder="Ex.: Pastilha de freio" required value="<?= h(raw($form, 'nome')) ?>"></div>
    <div class="field"><label for="categoria">Categoria</label><input id="categoria" name="categoria" list="categorias" maxlength="60" required value="<?= h(raw($form, 'categoria')) ?>"><datalist id="categorias"><option value="Freios"><option value="Lubrificantes"><option value="Transmissão"><option value="Motor"><option value="Elétrica"><option value="Pneus"></datalist></div>
    <div class="field"><label for="compatibilidade">Compatibilidade</label><input id="compatibilidade" name="compatibilidade" maxlength="100" placeholder="Ex.: Yamaha Factor 150" required value="<?= h(raw($form, 'compatibilidade')) ?>"></div>
    <div class="field"><label for="preco">Preço de venda (R$)</label><input id="preco" name="preco" type="number" min="0.01" max="9999999.99" step="0.01" required value="<?= h(raw($form, 'preco')) ?>"></div>
    <div class="field"><label for="quantidade_minima">Estoque mínimo</label><input id="quantidade_minima" name="quantidade_minima" type="number" min="0" max="1000000" step="1" required value="<?= h(raw($form, 'quantidade_minima') !== '' ? raw($form, 'quantidade_minima') : '5') ?>"></div>
    <?php if (!raw($form, 'id')): ?><div class="field"><label for="quantidade">Quantidade inicial</label><input id="quantidade" name="quantidade" type="number" min="0" max="1000000" step="1" required value="<?= h(raw($form, 'quantidade') ?: '0') ?>"></div><?php endif; ?>
    <div class="form-actions"><button type="submit">Salvar peça</button><?php if (raw($form, 'id')): ?><a class="button secondary" href="index.php?opcao=produto">Cancelar edição</a><?php endif; ?><span class="help">Use o Controle de Estoque para registrar entradas e saídas.</span></div>
</form>
<div class="section-heading divided"><h2>Peças cadastradas</h2></div>
<?php if (!$data['rows']): ?><p class="empty-state">Nenhuma peça cadastrada. Inclua óleo 20W50, pastilhas de freio ou kits de relação.</p><?php else: ?>
<div class="table-wrap" tabindex="0" role="region" aria-label="Catálogo de peças"><table><thead><tr><th scope="col">Peça / SKU</th><th scope="col">Categoria / Compatibilidade</th><th scope="col">Preço</th><th scope="col">Saldo / Mínimo</th><th scope="col">Ações</th></tr></thead><tbody>
<?php foreach ($data['rows'] as $row): ?><tr><td><strong><?= h($row['nome']) ?></strong><small><?= h($row['sku']) ?></small></td><td><?= h($row['categoria']) ?><small><?= h($row['compatibilidade']) ?></small></td><td class="numeric"><?= h(money($row['preco'])) ?></td><td><?= h($row['quantidade']) ?> / <?= h($row['quantidade_minima']) ?></td><td><div class="row-actions"><a class="text-action" href="index.php?opcao=produto&amp;editar=<?= h($row['id']) ?>" aria-label="Editar <?= h($row['nome']) ?>">Editar</a><form method="post" action="index.php?opcao=produto" data-confirm="Excluir esta peça? Peças com histórico serão preservadas."><?php csrf_input(); ?><input type="hidden" name="acao" value="excluir"><input type="hidden" name="id" value="<?= h($row['id']) ?>"><button class="text-action danger" aria-label="Excluir <?= h($row['nome']) ?>">Excluir</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?>
