<?php
$openOrders = array_filter($data['orders'], static function ($order) { return $order['status'] !== 'concluida'; });
$salePost = $error && raw($_POST, 'acao') === 'vender' ? $_POST : [];
$submittedIds = $salePost['produto_id'] ?? [''];
$submittedQuantities = $salePost['quantidade'] ?? ['1'];
if (!is_array($submittedIds) || !$submittedIds || count($submittedIds) > 30) { $submittedIds = ['']; }
if (!is_array($submittedQuantities)) { $submittedQuantities = []; }
$itemNumber = 0;
?>
<div class="no-print">
<div class="section-heading"><div><p class="eyebrow">ATENDIMENTOS &amp; SERVIÇOS</p><h2>Ordens de serviço</h2></div><span class="badge"><?= count($openOrders) ?> em aberto</span></div>
<details class="form-details"><summary>Abrir uma ordem de serviço</summary>
    <form method="post" action="index.php?opcao=vendas" class="form-grid">
        <?php csrf_input(); ?><input type="hidden" name="acao" value="abrir_os">
        <div class="field full"><label for="os_cliente">Cliente e moto</label><select id="os_cliente" name="cliente_id" required><option value="">Selecione o cliente</option><?php foreach ($data['clients'] as $client): ?><option value="<?= h($client['id']) ?>" <?= raw($_POST, 'acao') === 'abrir_os' && raw($_POST, 'cliente_id') === (string) $client['id'] ? 'selected' : '' ?>><?= h($client['nome']) ?> — CPF <?= h($client['cpf']) ?> — <?= h($client['modelo_moto']) ?> / <?= h($client['placa_moto']) ?></option><?php endforeach; ?></select></div>
        <div class="field full"><label for="os_descricao">Serviço solicitado</label><textarea id="os_descricao" name="descricao" maxlength="500" rows="3" placeholder="Ex.: Revisão do freio dianteiro e troca de óleo" required><?= raw($_POST, 'acao') === 'abrir_os' ? h(raw($_POST, 'descricao')) : '' ?></textarea></div>
        <div class="form-actions"><button type="submit" <?= !$data['clients'] ? 'disabled' : '' ?>>Abrir ordem de serviço</button></div>
    </form>
</details>
<?php if (!$data['orders']): ?><p class="empty-state compact">Nenhuma ordem de serviço aberta.</p><?php else: ?>
<div class="table-wrap" tabindex="0" role="region" aria-label="Ordens de serviço"><table><thead><tr><th scope="col">OS / Data</th><th scope="col">Cliente / CPF</th><th scope="col">Moto / Placa</th><th scope="col">Serviço</th><th scope="col">Situação</th></tr></thead><tbody>
<?php foreach ($data['orders'] as $order): ?><tr><td>#<?= h($order['id']) ?><small><?= h(date('d/m/Y', strtotime($order['criado_em']))) ?></small></td><td><?= h($order['nome']) ?><small><?= h($order['cpf']) ?></small></td><td><?= h($order['modelo_moto']) ?><small><?= h($order['placa_moto']) ?></small></td><td><?= h($order['descricao']) ?></td><td><span class="badge"><?= h(['aberta' => 'Aberta', 'em_andamento' => 'Em andamento', 'concluida' => 'Concluída'][$order['status']]) ?></span><?php if ($order['status'] === 'aberta'): ?><form method="post" action="index.php?opcao=vendas"><?php csrf_input(); ?><input type="hidden" name="acao" value="iniciar_os"><input type="hidden" name="id" value="<?= h($order['id']) ?>"><button class="text-action" aria-label="Iniciar OS <?= h($order['id']) ?>">Iniciar serviço</button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?>
<div class="section-heading divided"><div><p class="eyebrow">PEÇAS &amp; MÃO DE OBRA</p><h2>Registrar venda</h2></div></div>
<?php if (!$data['clients']): ?><p class="empty-state">Cadastre um cliente antes de registrar vendas ou abrir ordens de serviço.</p><a class="button" href="index.php?opcao=cliente">Cadastrar cliente</a><?php else: ?>
<form method="post" action="index.php?opcao=vendas" class="form-grid" id="sale-form">
    <?php csrf_input(); ?><input type="hidden" name="acao" value="vender">
    <div class="field"><label for="venda_cliente">Cliente</label><select id="venda_cliente" name="cliente_id" required><option value="">Selecione o cliente</option><?php foreach ($data['clients'] as $client): ?><option value="<?= h($client['id']) ?>" <?= raw($salePost, 'cliente_id') === (string) $client['id'] ? 'selected' : '' ?>><?= h($client['nome']) ?> — <?= h($client['placa_moto']) ?></option><?php endforeach; ?></select></div>
    <div class="field"><label for="ordem_servico_id">Ordem de serviço <span>(opcional)</span></label><select id="ordem_servico_id" name="ordem_servico_id"><option value="">Venda sem OS</option><?php foreach ($openOrders as $order): ?><option value="<?= h($order['id']) ?>" data-cliente="<?= h($order['cliente_id']) ?>" <?= raw($salePost, 'ordem_servico_id') === (string) $order['id'] ? 'selected' : '' ?>>OS #<?= h($order['id']) ?> — <?= h($order['nome']) ?></option><?php endforeach; ?></select></div>
    <fieldset class="full sale-items"><legend>Peças da venda</legend><p class="help">O preço é obtido do catálogo. Para um serviço sem peças, deixe a seleção vazia.</p><div id="sale-items">
        <?php foreach ($submittedIds as $key => $selectedId): $n = $itemNumber++; ?>
        <div class="sale-item"><div class="field"><label for="sale-product-<?= $n ?>">Peça <?= $n + 1 ?></label><select id="sale-product-<?= $n ?>" name="produto_id[]" data-sale-product><option value="">Sem peça</option><?php foreach ($data['products'] as $product): ?><option value="<?= h($product['id']) ?>" data-price="<?= h(cents($product['preco'], true)) ?>" <?= is_scalar($selectedId) && (string) $selectedId === (string) $product['id'] ? 'selected' : '' ?>><?= h($product['nome']) ?> — <?= h(money($product['preco'])) ?> — saldo <?= h($product['quantidade']) ?></option><?php endforeach; ?></select></div><div class="field"><label for="sale-quantity-<?= $n ?>">Quantidade <?= $n + 1 ?></label><input id="sale-quantity-<?= $n ?>" name="quantidade[]" type="number" min="1" max="1000000" step="1" required value="<?= h(isset($submittedQuantities[$key]) && is_scalar($submittedQuantities[$key]) ? $submittedQuantities[$key] : '1') ?>" data-sale-quantity></div><button type="button" class="button secondary remove-item" aria-label="Remover peça <?= $n + 1 ?>">Remover</button></div>
        <?php endforeach; ?>
    </div><button type="button" class="button secondary" id="add-item" hidden>Adicionar outra peça</button></fieldset>
    <div class="field"><label for="servico">Serviço realizado <span>(obrigatório com mão de obra)</span></label><textarea id="servico" name="servico" maxlength="500" rows="3" placeholder="Ex.: Troca de óleo e revisão de freios"><?= h(raw($salePost, 'servico')) ?></textarea></div>
    <div class="field"><label for="mao_obra">Mão de obra (R$)</label><input id="mao_obra" name="mao_obra" type="number" min="0" max="9999999.99" step="0.01" required value="<?= h(raw($salePost, 'mao_obra') ?: '0.00') ?>"><p class="help">A OS selecionada será concluída ao salvar a venda.</p></div>
    <div class="form-actions"><button type="submit">Registrar venda e baixar estoque</button><output id="sale-total" class="sale-total" aria-live="polite"></output></div>
</form>
<template id="sale-item-template"><div class="sale-item"><div class="field"><label data-product-label>Peça</label><select name="produto_id[]" data-sale-product><option value="">Sem peça</option><?php foreach ($data['products'] as $product): ?><option value="<?= h($product['id']) ?>" data-price="<?= h(cents($product['preco'], true)) ?>"><?= h($product['nome']) ?> — <?= h(money($product['preco'])) ?> — saldo <?= h($product['quantidade']) ?></option><?php endforeach; ?></select></div><div class="field"><label data-quantity-label>Quantidade</label><input name="quantidade[]" type="number" min="1" max="1000000" step="1" required value="1" data-sale-quantity></div><button type="button" class="button secondary remove-item">Remover</button></div></template>
<?php endif; ?>
</div>
<section id="relatorio" class="report" aria-labelledby="report-title">
    <div class="section-heading divided"><div><p class="eyebrow">MOVIMENTAÇÃO FINANCEIRA</p><h2 id="report-title">Relatório de vendas da oficina</h2></div><button type="button" class="print-button no-print" id="print-report" hidden>Imprimir / Salvar PDF</button></div>
    <form method="get" action="index.php" class="filter-form no-print"><input type="hidden" name="opcao" value="vendas"><div class="field"><label for="inicio">Data inicial</label><input type="date" id="inicio" name="inicio" required value="<?= h($data['start']) ?>"></div><div class="field"><label for="fim">Data final</label><input type="date" id="fim" name="fim" required value="<?= h($data['end']) ?>"></div><button type="submit">Filtrar período</button></form>
    <?php if ($data['filter_error']): ?><p class="mensagem erro no-print" role="alert"><?= h($data['filter_error']) ?> Exibindo o mês atual.</p><?php endif; ?>
    <p class="report-period">Período: <?= h(date('d/m/Y', strtotime($data['start']))) ?> a <?= h(date('d/m/Y', strtotime($data['end']))) ?> <span aria-hidden="true">·</span> Emitido em <?= h(date('d/m/Y H:i')) ?></p>
    <div class="report-summary"><div><span>Vendas no período</span><strong><?= count($data['sales']) ?></strong></div><div><span>Faturamento total</span><strong><?= h(money($data['total'])) ?></strong></div></div>
    <?php if (!$data['sales']): ?><p class="empty-state">Nenhuma venda registrada neste período.</p><?php else: ?>
    <div class="table-wrap" tabindex="0" role="region" aria-label="Vendas do período"><table class="report-table"><thead><tr><th scope="col">Venda / Data</th><th scope="col">Cliente / Moto</th><th scope="col">Peças e serviços</th><th scope="col">Mão de obra</th><th scope="col">Total</th></tr></thead><tbody>
    <?php foreach ($data['sales'] as $sale): ?><tr><td>#<?= h($sale['id']) ?><small><?= h(date('d/m/Y H:i', strtotime($sale['criado_em']))) ?></small><?php if ($sale['ordem_servico_id']): ?><small>OS #<?= h($sale['ordem_servico_id']) ?></small><?php endif; ?></td><td><strong><?= h($sale['cliente_nome']) ?></strong><small>CPF <?= h($sale['cliente_cpf']) ?></small><small><?= h($sale['modelo_moto']) ?> / <?= h($sale['placa_moto']) ?></small></td><td><?php foreach ($data['items'][$sale['id']] ?? [] as $item): ?><span class="report-item"><?= h($item['quantidade']) ?> × <?= h($item['produto_nome']) ?> <small><?= h(money($item['preco_unitario'])) ?> / unidade</small></span><?php endforeach; ?><?php if ($sale['servico']): ?><span class="report-item"><?= h($sale['servico']) ?></span><?php endif; ?></td><td class="numeric"><?= h(money($sale['mao_obra'])) ?></td><td class="numeric report-value"><?= h(money($sale['total'])) ?></td></tr><?php endforeach; ?>
    </tbody><tfoot><tr><th scope="row" colspan="4">Total do período</th><td class="numeric report-value"><?= h(money($data['total'])) ?></td></tr></tfoot></table></div><?php endif; ?>
    <p class="help no-print">Use “Imprimir / Salvar PDF” e escolha “Salvar como PDF” no navegador. O relatório contém apenas o período filtrado. Também é possível usar Ctrl+P.</p>
    <p class="print-only print-footer">Moto Oficina — Relatório gerencial de vendas. Este documento não substitui uma nota fiscal.</p>
</section>
